# Generated by Django 4.2.7 on 2024-05-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=128)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('division', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.division')),
            ],
        ),
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_name', models.CharField(max_length=255)),
                ('disconnections', models.CharField(max_length=255)),
                ('protections', models.CharField(default='Не требуется', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('access_group', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('access_group', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата настройки')),
                ('winder', models.IntegerField(verbose_name='Моталка №')),
                ('roll', models.IntegerField(verbose_name='Формирующий ролик')),
                ('task', models.FloatField(verbose_name='Задание с клином в привод, %')),
                ('cspd', models.BooleanField(default=False, verbose_name='Корректировка фактической скорости')),
                ('tspd', models.FloatField(default=10.0, verbose_name='Выставленная скорость по заданию, м/с')),
                ('bmav', models.IntegerField(verbose_name='Изм. угл. факт. скорость до корр., об/мин')),
                ('bemf', models.FloatField(verbose_name='Значение параметра P115.2 до изменения')),
                ('amav', models.IntegerField(verbose_name='Изм. угл. факт. скорость после корр., об/мин')),
                ('aemf', models.FloatField(verbose_name='Значение параметра P115.2 после изменения')),
                ('corr', models.BooleanField(default=True, verbose_name='Корректировка скоростей')),
            ],
        ),
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('access_group', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default='')),
                ('accountable_name', models.CharField(default='Не назначается', max_length=128)),
                ('allower_name', models.CharField(default='оперативному персоналу', max_length=128)),
                ('errand', models.CharField(max_length=512)),
                ('add_instrs', models.CharField(max_length=512)),
                ('extrad_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.brigade')),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.company')),
                ('division', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.division')),
                ('interventions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.interventions')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.issuer')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.member')),
                ('watching', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.watching')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brigade')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='grey', max_length=255)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.division')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('aggregate', models.CharField(max_length=100)),
                ('cabinet', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location')),
            ],
        ),
        migrations.AddField(
            model_name='brigade',
            name='members',
            field=models.ManyToManyField(through='main.Membership', to='main.member'),
        ),
    ]
