# Generated by Django 4.2.7 on 2024-05-19 09:57

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Наименование категории')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории инструкций',
                'verbose_name_plural': 'Категории инструкций',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Группа инструкций')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Группа инструкций',
                'verbose_name_plural': 'Группа инструкций',
            },
        ),
        migrations.CreateModel(
            name='Manuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Наименование инструкции')),
                ('image', models.ImageField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='C:\\Users\\Mike\\Projects\\aepp\\backend'), upload_to='manuals/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])], verbose_name='Картинка инструкции')),
                ('link', models.FileField(null=True, upload_to='manuals/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categories', verbose_name='Категория')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Инструкции',
                'verbose_name_plural': 'Инструкции',
            },
        ),
    ]
