# Generated by Django 4.2.7 on 2023-11-18 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="division_id",
            new_name="division",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="group_id",
            new_name="group",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="brigade_id",
            new_name="brigade",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="company_id",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="division_id",
            new_name="division",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="issuer_id",
            new_name="issuer",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="producer_id",
            new_name="producer",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="watching_id",
            new_name="watching",
        ),
    ]
