# Generated by Django 4.2.7 on 2024-05-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_groups_manuals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuals',
            name='link',
        ),
    ]
